name: Deploy to Timeweb
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Force IPv4
        run: sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /a-invest/public_html/
          timeout: 60000
          exclude: |
            **/.git*
            **/.git*/**
            _materials/**
            _distributions/**
            _template.html
            README.md
            .gitignore
